### ISSUE TITLE
Sending Device Description info

### ISSUE THREAD

**Issue by shakthimaan** [bazwilliams/node-ssdp#3]
How does one send "Device Description" info from a Device to the Control Point using this module?

**Comment by bazwilliams** [comment]
The event handlers are expected to supply a function. This function will be invoked with a device descriptor object.

**Comment by shakthimaan** [comment]
Sorry, I didn't quite understand that. Can you please provide an example?

**Comment by bazwilliams** [comment]
The code is used in this file https://github.com/bazwilliams/openhome-monitor-service/blob/master/index.js

You can see the event handlers and the passed in function
